server:
  port: 8081
  servlet:
    context-path: /demo
jwt:
  secret: 30498tvygruerhpuv7dfb7d9ay84tyhg
  lifetime: 10m

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./user;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  main:
    allow-circular-references: true

